version: '3.7'

services:
  oracle:
    build:
      context: .
      dockerfile: contrib/images/slinky.e2e.oracle.Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
  prometheus:
    links:
      - "oracle:oracle"
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./contrib/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
