###############################################################################
###                              Metrics                                    ###
###############################################################################
# MetricsConfig TOML Configuration

# PrometheusServerAddress is the address of the Prometheus server that the oracle will expose metrics to.
prometheus_server_address = "localhost:8000"

# OracleMetrics is the config for the oracle metrics
[oracle_metrics]

# Enabled indicates whether metrics should be enabled
enabled = true

# AppMetrics is the config for the app metrics
[app_metrics]
# Enabled indicates whether metrics should be enabled
enabled = true

# ValidatorConsAddress is the validator's consensus address
validator_cons_address = ""