update_interval = "1.5s"
production = true

[[providers]]
  name = "uniswap"
  [providers.api]
    enabled = true
    timeout = "500ms"
    interval = "1s"
    max_queries = 1
    atomic = false
    url = "https://eth.public-rpc.com/"
    name = "uniswap"
    [providers.api.evm]
      enabled = true
  [providers.web_socket]
    enabled = false
    max_buffer_size = 0
    reconnection_timeout = "0s"
    wss = ""
    name = ""
    read_buffer_size = 0
    write_buffer_size = 0
    handshake_timeout = "0s"
    enable_compression = false
    read_deadline = "0s"
    write_deadline = "0s"
    ping_interval = "0s"
    max_read_error_count = 0
    max_subscriptions_per_connection = 0
  [providers.market_config]
    name = "uniswap"
    [providers.market_config.currency_pair_to_market_configs]
      [providers.market_config.currency_pair_to_market_configs."WETH/USDC"]
        ticker = "WETH/USDC"
        [providers.market_config.currency_pair_to_market_configs."WETH/USDC".currency_pair]
          Base = "WETH"
          Quote = "USDC"

[market]
  [market.currency_pairs]
    [market.currency_pairs."WETH/USDC"]
      [market.currency_pairs."WETH/USDC".currency_pair]
        Base = "WETH"
        Quote = "USDC"
  [market.aggregated_feeds]
    [market.aggregated_feeds."WETH/USDC"]
      conversions = [[{invert = false, currency_pair = {Base = "WETH", Quote = "USDC"}}]]
      [market.aggregated_feeds."WETH/USDC".currency_pair]
        Base = "WETH"
        Quote = "USDC"

[metrics]
  prometheus_server_address = "0.0.0.0:8002"
  enabled = true
