###############################################################################
###                           CoinMarketCap                                 ###
###############################################################################
# This section contains the configuration for the CoinMarketCap API. This meant to be
# used in a testing environment as this API is not production ready.

# APIKey is the API key used to make requests to the CoinMarketCap API.
api_key = ""

# TokenNameToMetadata is a map of token names to their metadata.
[token_name_to_symbol]
  "BITCOIN" = "BTC"
  "USD" = "USD"
  # Add more token name-to-symbol mappings as needed