###############################################################################
###                                Coinbase                                 ###
###############################################################################
# This section contains the configuration for the Coinbase API. This meant to be
# used in a testing environment as this API is not production ready.

# NameToSymbol is a map of currency names to their symbols.
[name_to_symbol]
  "BITCOIN" = "BTC"
  "USD" = "USD"
  # Add more currency mappings as needed
